/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_nullschool_util_RdrandEngine */

#ifndef _Included_net_nullschool_util_RdrandEngine
#define _Included_net_nullschool_util_RdrandEngine
#ifdef __cplusplus
extern "C" {
#endif
#undef net_nullschool_util_RdrandEngine_serialVersionUID
#define net_nullschool_util_RdrandEngine_serialVersionUID -2991854161009191830i64
#undef net_nullschool_util_RdrandEngine_serialVersionUID
#define net_nullschool_util_RdrandEngine_serialVersionUID 1i64
#undef net_nullschool_util_RdrandEngine_serialVersionUID
#define net_nullschool_util_RdrandEngine_serialVersionUID 1i64
/*
 * Class:     net_nullschool_util_RdrandEngine
 * Method:    isRdrandSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_nullschool_util_RdrandEngine_isRdrandSupported
  (JNIEnv *, jclass);

/*
 * Class:     net_nullschool_util_RdrandEngine
 * Method:    engineNextInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_nullschool_util_RdrandEngine_engineNextInt
  (JNIEnv *, jobject);

/*
 * Class:     net_nullschool_util_RdrandEngine
 * Method:    engineNextLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_nullschool_util_RdrandEngine_engineNextLong
  (JNIEnv *, jobject);

/*
 * Class:     net_nullschool_util_RdrandEngine
 * Method:    engineNextBytes
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_net_nullschool_util_RdrandEngine_engineNextBytes
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
