/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_nullschool_util_RdrandEngine_NativeMethods */

#ifndef _Included_net_nullschool_util_RdrandEngine_NativeMethods
#define _Included_net_nullschool_util_RdrandEngine_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_nullschool_util_RdrandEngine_NativeMethods
 * Method:    isRdrandSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_nullschool_util_RdrandEngine_00024NativeMethods_isRdrandSupported
  (JNIEnv *, jclass);

/*
 * Class:     net_nullschool_util_RdrandEngine_NativeMethods
 * Method:    rdrand32
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_nullschool_util_RdrandEngine_00024NativeMethods_rdrand32
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_nullschool_util_RdrandEngine_NativeMethods
 * Method:    rdrand64
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_net_nullschool_util_RdrandEngine_00024NativeMethods_rdrand64
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_nullschool_util_RdrandEngine_NativeMethods
 * Method:    rdrandBytes
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_net_nullschool_util_RdrandEngine_00024NativeMethods_rdrandBytes
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
