/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_nullschool_util_RdRandEngine */

#ifndef _Included_net_nullschool_util_RdRandEngine
#define _Included_net_nullschool_util_RdRandEngine
#ifdef __cplusplus
extern "C" {
#endif
#undef net_nullschool_util_RdRandEngine_serialVersionUID
#define net_nullschool_util_RdRandEngine_serialVersionUID -2991854161009191830LL
#undef net_nullschool_util_RdRandEngine_serialVersionUID
#define net_nullschool_util_RdRandEngine_serialVersionUID 1LL
#undef net_nullschool_util_RdRandEngine_serialVersionUID
#define net_nullschool_util_RdRandEngine_serialVersionUID 1LL
/*
 * Class:     net_nullschool_util_RdRandEngine
 * Method:    isRdRandSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_nullschool_util_RdRandEngine_isRdRandSupported
  (JNIEnv *, jclass);

/*
 * Class:     net_nullschool_util_RdRandEngine
 * Method:    engineNextInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_nullschool_util_RdRandEngine_engineNextInt
  (JNIEnv *, jobject);

/*
 * Class:     net_nullschool_util_RdRandEngine
 * Method:    engineNextLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_nullschool_util_RdRandEngine_engineNextLong
  (JNIEnv *, jobject);

/*
 * Class:     net_nullschool_util_RdRandEngine
 * Method:    engineNextBytes
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_net_nullschool_util_RdRandEngine_engineNextBytes
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
